"""Generate docs/quickstart.md by running real commands on an example (M8-T02).

CI re-runs this and diffs — the documented output cannot rot.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _run(args: list[str], cwd: Path) -> str:
    """Run a command; audit exits 1 on findings — capture output regardless."""
    exe = shutil.which("reprollm") or str(ROOT / ".venv/bin/reprollm")
    result = subprocess.run([exe, *args], cwd=cwd, capture_output=True, text=True)
    if result.returncode not in (0, 1):
        raise SystemExit(f"{args} failed: {result.stderr}")
    return result.stdout.rstrip()


def scrub(text: str, work: Path) -> str:
    """Remove tempdir paths so the document is reproducible across runs."""
    return text.replace(str(work), "examples/hf_vllm_eval")


def main(check: bool = False) -> int:
    steps: list[tuple[str, list[str], str]] = [
        ("Zero-config audit (Level 0)", ["audit", ".", "--no-color"], "audit"),
        ("Scaffold a manifest from detection", ["init", ".", "--force"], "init"),
        ("Audit again — now at Level 1", ["audit", ".", "--no-color"], "audit-l1"),
    ]
    body = [
        "# Quick start",
        "",
        "Everything below is real output, regenerated by CI from",
        "`examples/hf_vllm_eval` — the guide cannot go stale.",
        "",
        "```bash",
        "pip install reprollm",
        "git clone https://github.com/EnumaElish123/ReproLLM.git   # for the example",
        "cd ReproLLM/examples/hf_vllm_eval",
        "```",
        "",
    ]
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "hf_vllm_eval"
        fixture = ROOT / "tests" / "fixtures" / "repos" / "hf_vllm_eval"
        shutil.copytree(fixture / "tree", work)
        manifest = fixture / "manifests" / "complete.yaml"
        (work / "reprollm.yaml").write_text(
            manifest.read_text(encoding="utf-8") + "\n", encoding="utf-8"
        )
        # A deterministic git repository — the runner's git identity must not
        # influence the documented output.
        import os
        import subprocess as sp

        env = {**os.environ,
               "GIT_AUTHOR_NAME": "Demo", "GIT_AUTHOR_EMAIL": "demo@localhost",
               "GIT_COMMITTER_NAME": "Demo", "GIT_COMMITTER_EMAIL": "demo@localhost",
               "GIT_AUTHOR_DATE": "2026-01-01T00:00:00Z",
               "GIT_COMMITTER_DATE": "2026-01-01T00:00:00Z"}
        sp.run(["git", "init", "-q"], cwd=work, check=True)
        sp.run(["git", "add", "-A"], cwd=work, check=True, env=env)
        sp.run(["git", "commit", "-qm", "demo"], cwd=work, check=True, env=env)
        for title, args, _tag in steps:
            output = _run(args, work)
            body.append(f"## {title}")
            body.append("")
            body.append(f"$ reprollm {' '.join(args)}")
            body.append("```text")
            body.append(scrub(output, work))
            body.append("```")
            body.append("")
    target = ROOT / "docs" / "quickstart.md"
    body.append("---")
    body.append(
        "Continue: [concepts](concepts.md) · [CLI reference](cli.md) · [why ReproLLM](why.md)"
    )
    text = "\n".join(body) + "\n"
    if check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != text:
            print("docs/quickstart.md is stale; regenerate with scripts/gen_quickstart.py")
            return 1
        print("quickstart fresh")
        return 0
    target.write_text(text, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(check="--check" in sys.argv))
